default_agent: dcisionai_manufacturing_mcp_v1
agents:
  dcisionai_manufacturing_mcp_v1:
    name: dcisionai_manufacturing_mcp_v1
    entrypoint: src/mcp_server/DcisionAI_Manufacturing_Agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: '808953421331'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: true
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    oauth_configuration: null
