default_agent: agentcore_agent
agents:
  agentcore_agent:
    name: agentcore_agent
    entrypoint: agentcore_agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::808953421331:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-db02173b19
      execution_role_auto_create: false
      account: '808953421331'
      region: us-east-1
      ecr_repository: 808953421331.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agentcore_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agentcore_agent-X2iSRn9X6Z
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:808953421331:runtime/agentcore_agent-X2iSRn9X6Z
      agent_session_id: 7d2c4e2f-3e85-4bc3-8b9e-9f35060c28fc
    codebuild:
      project_name: bedrock-agentcore-agentcore_agent-builder
      execution_role: arn:aws:iam::808953421331:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-db02173b19
      source_bucket: bedrock-agentcore-codebuild-sources-808953421331-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
