default_agent: dcisionai_agent

agents:
  dcisionai_agent:
    name: dcisionai_agent
    entrypoint: dcisionai_agentcore_agent.py
    requirements_file: requirements.txt
    protocol: HTTP
    aws:
      region: us-east-1
      account: "808953421331"
      execution_role: "arn:aws:iam::808953421331:role/dcisionai-lambda-execution-role-production"
    deployment:
      container_runtime: null  # Will use default
      ecr_repository: null  # Will be auto-created
      disable_otel: false
      auto_create_ecr: true
    authorizer:
      config: null  # No OAuth for now
