default_agent: bedrock_agentcore_mcp_server
agents:
  bedrock_agentcore_mcp_server:
    name: bedrock_agentcore_mcp_server
    entrypoint: bedrock_agentcore_mcp_server.py
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::808953421331:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-d4d8a25ff7
      execution_role_auto_create: false
      account: '808953421331'
      region: us-east-1
      ecr_repository: 808953421331.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-bedrock_agentcore_mcp_server
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: bedrock_agentcore_mcp_server-uZ4MxJ2bNZ
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:808953421331:runtime/bedrock_agentcore_mcp_server-uZ4MxJ2bNZ
      agent_session_id: 570b3ea3-ed80-446a-8420-b0222f827cc9
    codebuild:
      project_name: bedrock-agentcore-bedrock_agentcore_mcp_server-builder
      execution_role: arn:aws:iam::808953421331:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-d4d8a25ff7
      source_bucket: bedrock-agentcore-codebuild-sources-808953421331-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: bedrock_agentcore_mcp_server_mem-DqJxGf3Wn0
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:808953421331:memory/bedrock_agentcore_mcp_server_mem-DqJxGf3Wn0
      memory_name: bedrock_agentcore_mcp_server_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
