AWSTemplateFormatVersion: '2010-09-09'
Description: 'DcisionAI Platform - Tenant-Dedicated AWS Bedrock Inference Profiles'

Parameters:
  Environment:
    Type: String
    Default: production
    Description: Environment name (dev, staging, production)
    AllowedValues: [dev, staging, production]
  
  PlatformName:
    Type: String
    Default: dcisionai
    Description: Platform name for resource naming
  
  BaseModelId:
    Type: String
    Default: anthropic.claude-3-sonnet-20240229-v1:0
    Description: Base model ID for inference profiles
    AllowedValues:
      - anthropic.claude-3-sonnet-20240229-v1:0
      - anthropic.claude-3-haiku-20240307-v1:0
      - amazon.titan-text-express-v1:0
      - meta.llama2-13b-chat-v1:0

Resources:
  # Gold Tier Inference Profile - High Performance, Multi-Region
  GoldTierInferenceProfile:
    Type: AWS::Bedrock::InferenceProfile
    Properties:
      ProfileName: !Sub '${PlatformName}-gold-tier-${Environment}'
      Description: 'Gold tier inference profile for enterprise customers with high performance requirements'
      ModelId: !Ref BaseModelId
      InferenceProfileConfig:
        InferenceProfileType: 'CrossRegion'
        CrossRegionConfig:
          Regions:
            - us-east-1
            - us-west-2
            - eu-west-1
            - ap-southeast-1
          OptimizationType: 'Latency'
          CostOptimization: false
          ReliabilityOptimization: true
  
  # Pro Tier Inference Profile - Balanced Performance
  ProTierInferenceProfile:
    Type: AWS::Bedrock::InferenceProfile
    Properties:
      ProfileName: !Sub '${PlatformName}-pro-tier-${Environment}'
      Description: 'Pro tier inference profile for professional customers with balanced performance'
      ModelId: !Ref BaseModelId
      InferenceProfileConfig:
        InferenceProfileType: 'CrossRegion'
        CrossRegionConfig:
          Regions:
            - us-east-1
            - us-west-2
            - eu-west-1
          OptimizationType: 'Balanced'
          CostOptimization: true
          ReliabilityOptimization: false
  
  # Free Tier Inference Profile - Cost Optimized
  FreeTierInferenceProfile:
    Type: AWS::Bedrock::InferenceProfile
    Properties:
      ProfileName: !Sub '${PlatformName}-free-tier-${Environment}'
      Description: 'Free tier inference profile for basic customers with cost optimization'
      ModelId: !Ref BaseModelId
      InferenceProfileConfig:
        InferenceProfileType: 'CrossRegion'
        CrossRegionConfig:
          Regions:
            - us-east-1
            - us-west-2
          OptimizationType: 'Cost'
          CostOptimization: true
          ReliabilityOptimization: false
  
  # Manufacturing Domain Specific Profiles
  ManufacturingLatencyProfile:
    Type: AWS::Bedrock::InferenceProfile
    Properties:
      ProfileName: !Sub '${PlatformName}-manufacturing-latency-${Environment}'
      Description: 'Manufacturing domain inference profile optimized for low latency'
      ModelId: !Ref BaseModelId
      InferenceProfileConfig:
        InferenceProfileType: 'CrossRegion'
        CrossRegionConfig:
          Regions:
            - us-east-1
            - us-west-2
          OptimizationType: 'Latency'
          CostOptimization: false
          ReliabilityOptimization: false
  
  ManufacturingCostProfile:
    Type: AWS::Bedrock::InferenceProfile
    Properties:
      ProfileName: !Sub '${PlatformName}-manufacturing-cost-${Environment}'
      Description: 'Manufacturing domain inference profile optimized for cost'
      ModelId: !Ref BaseModelId
      InferenceProfileConfig:
        InferenceProfileType: 'CrossRegion'
        CrossRegionConfig:
          Regions:
            - us-east-1
            - us-west-2
            - eu-west-1
          OptimizationType: 'Cost'
          CostOptimization: true
          ReliabilityOptimization: false
  
  ManufacturingReliabilityProfile:
    Type: AWS::Bedrock::InferenceProfile
    Properties:
      ProfileName: !Sub '${PlatformName}-manufacturing-reliability-${Environment}'
      Description: 'Manufacturing domain inference profile optimized for reliability'
      ModelId: !Ref BaseModelId
      InferenceProfileConfig:
        InferenceProfileType: 'CrossRegion'
        CrossRegionConfig:
          Regions:
            - us-east-1
            - us-west-2
            - eu-west-1
            - ap-southeast-1
          OptimizationType: 'Reliability'
          CostOptimization: false
          ReliabilityOptimization: true
  
  # Finance Domain Specific Profiles
  FinanceLatencyProfile:
    Type: AWS::Bedrock::InferenceProfile
    Properties:
      ProfileName: !Sub '${PlatformName}-finance-latency-${Environment}'
      Description: 'Finance domain inference profile optimized for low latency'
      ModelId: !Ref BaseModelId
      InferenceProfileConfig:
        InferenceProfileType: 'CrossRegion'
        CrossRegionConfig:
          Regions:
            - us-east-1
            - us-west-2
          OptimizationType: 'Latency'
          CostOptimization: false
          ReliabilityOptimization: false
  
  FinanceComplianceProfile:
    Type: AWS::Bedrock::InferenceProfile
    Properties:
      ProfileName: !Sub '${PlatformName}-finance-compliance-${Environment}'
      Description: 'Finance domain inference profile optimized for compliance and reliability'
      ModelId: !Ref BaseModelId
      InferenceProfileConfig:
        InferenceProfileType: 'CrossRegion'
        CrossRegionConfig:
          Regions:
            - us-east-1
            - us-west-2
            - eu-west-1
          OptimizationType: 'Reliability'
          CostOptimization: false
          ReliabilityOptimization: true
  
  # Pharma Domain Specific Profiles
  PharmaResearchProfile:
    Type: AWS::Bedrock::InferenceProfile
    Properties:
      ProfileName: !Sub '${PlatformName}-pharma-research-${Environment}'
      Description: 'Pharma domain inference profile for research workloads'
      ModelId: !Ref BaseModelId
      InferenceProfileConfig:
        InferenceProfileType: 'CrossRegion'
        CrossRegionConfig:
          Regions:
            - us-east-1
            - us-west-2
            - eu-west-1
          OptimizationType: 'Balanced'
          CostOptimization: true
          ReliabilityOptimization: true
  
  PharmaComplianceProfile:
    Type: AWS::Bedrock::InferenceProfile
    Properties:
      ProfileName: !Sub '${PlatformName}-pharma-compliance-${Environment}'
      Description: 'Pharma domain inference profile for compliance workloads'
      ModelId: !Ref BaseModelId
      InferenceProfileConfig:
        InferenceProfileType: 'CrossRegion'
        CrossRegionConfig:
          Regions:
            - us-east-1
            - us-west-2
            - eu-west-1
            - ap-southeast-1
          OptimizationType: 'Reliability'
          CostOptimization: false
          ReliabilityOptimization: true
  
  # IAM Role for Bedrock Access
  BedrockAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${PlatformName}-bedrock-access-${Environment}'
      Description: 'IAM role for DcisionAI Platform to access Bedrock Inference Profiles'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BedrockAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                  - bedrock:ListInferenceProfiles
                  - bedrock:GetInferenceProfile
                Resource: '*'
              - Effect: Allow
                Action:
                  - bedrock-runtime:InvokeModel
                  - bedrock-runtime:InvokeModelWithResponseStream
                Resource: '*'
  
  # CloudWatch Dashboard for Inference Profile Monitoring
  InferenceProfileDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${PlatformName}-inference-profiles-${Environment}'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/Bedrock", "InferenceRequests", "ProfileName", "${PlatformName}-gold-tier-${Environment}"],
                  [".", ".", ".", "${PlatformName}-pro-tier-${Environment}"],
                  [".", ".", ".", "${PlatformName}-free-tier-${Environment}"]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "us-east-1",
                "title": "Inference Requests by Tier",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/Bedrock", "InferenceLatency", "ProfileName", "${PlatformName}-gold-tier-${Environment}"],
                  [".", ".", ".", "${PlatformName}-pro-tier-${Environment}"],
                  [".", ".", ".", "${PlatformName}-free-tier-${Environment}"]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "us-east-1",
                "title": "Inference Latency by Tier",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/Bedrock", "InferenceErrors", "ProfileName", "${PlatformName}-gold-tier-${Environment}"],
                  [".", ".", ".", "${PlatformName}-pro-tier-${Environment}"],
                  [".", ".", ".", "${PlatformName}-free-tier-${Environment}"]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "us-east-1",
                "title": "Inference Errors by Tier",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/Bedrock", "InferenceCost", "ProfileName", "${PlatformName}-gold-tier-${Environment}"],
                  [".", ".", ".", "${PlatformName}-pro-tier-${Environment}"],
                  [".", ".", ".", "${PlatformName}-free-tier-${Environment}"]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "us-east-1",
                "title": "Inference Cost by Tier",
                "period": 300
              }
            }
          ]
        }

Outputs:
  GoldTierProfileArn:
    Description: 'Gold tier inference profile ARN'
    Value: !GetAtt GoldTierInferenceProfile.Arn
    Export:
      Name: !Sub '${PlatformName}-gold-tier-profile-arn-${Environment}'
  
  ProTierProfileArn:
    Description: 'Pro tier inference profile ARN'
    Value: !GetAtt ProTierInferenceProfile.Arn
    Export:
      Name: !Sub '${PlatformName}-pro-tier-profile-arn-${Environment}'
  
  FreeTierProfileArn:
    Description: 'Free tier inference profile ARN'
    Value: !GetAtt FreeTierInferenceProfile.Arn
    Export:
      Name: !Sub '${PlatformName}-free-tier-profile-arn-${Environment}'
  
  ManufacturingLatencyProfileArn:
    Description: 'Manufacturing latency profile ARN'
    Value: !GetAtt ManufacturingLatencyProfile.Arn
    Export:
      Name: !Sub '${PlatformName}-manufacturing-latency-profile-arn-${Environment}'
  
  ManufacturingCostProfileArn:
    Description: 'Manufacturing cost profile ARN'
    Value: !GetAtt ManufacturingCostProfile.Arn
    Export:
      Name: !Sub '${PlatformName}-manufacturing-cost-profile-arn-${Environment}'
  
  ManufacturingReliabilityProfileArn:
    Description: 'Manufacturing reliability profile ARN'
    Value: !GetAtt ManufacturingReliabilityProfile.Arn
    Export:
      Name: !Sub '${PlatformName}-manufacturing-reliability-profile-arn-${Environment}'
  
  BedrockAccessRoleArn:
    Description: 'Bedrock access IAM role ARN'
    Value: !GetAtt BedrockAccessRole.Arn
    Export:
      Name: !Sub '${PlatformName}-bedrock-access-role-arn-${Environment}'
  
  DashboardName:
    Description: 'CloudWatch dashboard name for inference profile monitoring'
    Value: !Ref InferenceProfileDashboard
    Export:
      Name: !Sub '${PlatformName}-inference-dashboard-name-${Environment}'
